#!/usr/bin/env ruby

git_bundles = [
	"https://github.com/astashov/vim-ruby-debugger.git",
	"https://github.com/msanders/snipmate.vim.git",
	"https://github.com/scrooloose/nerdtree.git",
	"https://github.com/timcharper/textile.vim.git",
	"https://github.com/tpope/vim-cucumber.git",
	"https://github.com/tpope/vim-fugitive.git",
	"https://github.com/tpope/vim-git.git",
	"https://github.com/tpope/vim-haml.git",
	"https://github.com/tpope/vim-markdown.git",
	"https://github.com/tpope/vim-rails.git",
	"https://github.com/tpope/vim-repeat.git",
	"https://github.com/tpope/vim-surround.git",
	"https://github.com/tpope/vim-vividchalk.git",
	"https://github.com/tsaleh/vim-align.git",
	"https://github.com/tsaleh/vim-matchit.git",
	"https://github.com/tsaleh/vim-shoulda.git",
	"https://github.com/tsaleh/vim-supertab.git",
	"https://github.com/vim-ruby/vim-ruby.git",
	"https://github.com/rosstimson/scala-vim-support.git",
	"https://github.com/mileszs/ack.vim.git",
	"https://github.com/vim-scripts/DirDiff.vim.git",
	"https://github.com/vim-scripts/YankRing.vim.git",
	"https://github.com/skammer/vim-css-color.git",
	"https://github.com/vim-scripts/python.vim.git",
	"https://github.com/mexpolk/vim-taglist.git",
	"https://github.com/bronson/vim-trailing-whitespace.git",
	"https://github.com/altercation/vim-colors-solarized.git",
	"https://github.com/vim-scripts/DoxygenToolkit.vim.git",
	"https://github.com/vim-scripts/mru.vim.git",
	"https://github.com/c9s/emoticon.vim.git",
	# "https://github.com/pix/vim-taglist.git",
	# "https://github.com/int3/vim-taglist-plus.git",
    "https://github.com/majutsushi/tagbar.git",
	"https://github.com/rupa/v.git",
	"https://github.com/vim-scripts/FuzzyFinder.git",
	"https://github.com/vim-scripts/L9.git",
	"https://github.com/Lokaltog/vim-powerline.git",
    "https://github.com/lunaru/vim-less.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  # ["gist",          "12732", "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle-autoupdate")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  begin
    `git clone #{url} #{dir}`
  end
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
